spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/mydb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.hexlet: info

sentry:
  dsn: https://32f8e938f883412355ab7bd37c5cd73f@o4510771997442048.ingest.de.sentry.io/4510772003274832
  send-default-pii: true